export const MetaData = {
	"Social Media": [
		{ meta: ["facebook", "fb", "messenger"], icon: "facebook.png" },
		{ meta: ["twitter"], icon: "twitter.png" },
		{ meta: ["snap", "snapchat"], icon: "snapchat.png" },
		{ meta: ["instagram", "ig", "insta"], icon: "instagram.svg" },
		{ meta: ["tumblr"], icon: "tumblr.png" },
		{ meta: ["youtube", "yt"], icon: "youtube.png" },
		{ meta: ["reddit"], icon: "reddit.png" },
		{ meta: ["twitch"], icon: "twitch.png" },
	],
	Education: [
		{ meta: ["medium"], icon: "medium.png" },
		{ meta: ["github"], icon: "github.png" },
		{ meta: ["stackoverflow", "so"], icon: "stackoverflow.png" },
		{ meta: ["stackexchange", "se", "exchange"], icon: "stackexchange.png" },
		{ meta: ["wiki", "wikipedia"], icon: "wikipedia.png" },
		{ meta: ["audible", "audio"], icon: "audible.png" },
	],
	Entertainment: [
		{ meta: ["apex", "apex legends"], icon: "apex.png" },
		{ meta: ["csgo", "counter strike"], icon: "csgo.png" },
		{ meta: ["orgin"], icon: "origin.png" },
		{ meta: ["itunes", "apple music"], icon: "itunes.png" },
		{ meta: ["steam"], icon: "steam.png" },
		{ meta: ["overwatch", "ow"], icon: "overwatch.png" },
		{ meta: ["playstation", "ps"], icon: "playstation.png" },
		{ meta: ["dota"], icon: "dota.png" },
		{ meta: ["terraria"], icon: "terraria.png" },
		{ meta: ["league", "lol", "league of legends"], icon: "league.png" },
		{ meta: ["netflix"], icon: "netflix.png" },
		{ meta: ["tinder", "dating app"], icon: "tinder.png" },
		{ meta: ["spotify"], icon: "spotify.png" },
	],
	Business: [
		{ meta: ["gmail", "google mail", "mail"], icon: "gmail.png" },
		{ meta: ["firebase", "google firebase"], icon: "firebase.png" },
		{ meta: ["google"], icon: "google.png" },
		{ meta: ["heroku"], icon: "heroku.png" },
		{ meta: ["aws", "amazon web service", "amazon"], icon: "aws.png" },
		{ meta: ["icloud"], icon: "icloud.png" },
		{ meta: ["mastercard"], icon: "mastercard.png" },
		{ meta: ["visa"], icon: "visa.png" },
		{ meta: ["microsoft", "windows", "ms"], icon: "microsoft.png" },
		{ meta: ["mongo", "mongodb", "nosql"], icon: "mongo.png" },
		{ meta: ["oracle"], icon: "oracle.png" },
		{ meta: ["onedrive"], icon: "onedrive.png" },
		{ meta: ["dropbox"], icon: "dropbox.png" },
		{ meta: ["drive", "gdrive", "googledrive"], icon: "drive.png" },
	],
	Communication: [
		{ meta: ["discord"], icon: "discord.png" },
		{ meta: ["slack"], icon: "slack.png" },
		{ meta: ["whatsapp"], icon: "whatsapp.png" },
		{ meta: ["skype"], icon: "skype.png" },
		{ meta: ["telegram"], icon: "telegram.png" },
		{ meta: ["kik"], icon: "kik.png" },
	],
	Shopping: [
		{ meta: ["amazon", "amazonprime"], icon: "amazon.png" },
		{ meta: ["ebay"], icon: "ebay.png" },
		{ meta: ["stripe"], icon: "stripe.png" },
		{ meta: ["applepay"], icon: "applepay.png" },
		{ meta: ["shopify"], icon: "shopify.png" },
	],
	Finance: [{ meta: ["paypal"], icon: "paypal.png" }],
	Other: "other.png",
};
